version: '3.8'

services:
  database:
    container_name: mariadb
    image: mariadb
    environment:
      - MYSQL_DATABASE=invoice
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/dbpassword
    volumes:
      - dbdata:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 3306
    secrets:
      - dbpassword
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    tty: true
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
  rails:
    container_name: rails7
    build: rails
    tty: true
    # RUN git clone https://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@github.com/ouaziz/rails_api_jwt.git app
    # command: cd /app && rails db:drop && rails db:create && rails db:migrate && rails db:seed
    # command: bash -c "bundle install"
    depends_on:
      - database
      - redis
    ports:
      - "3001:3000"
    volumes:
      - ./rails/assetsMgmt:/app
    env_file: 
      - .env
    environment: 
      RAILS_ENV: development
  redis:
    container_name: redis721
    image: redis:7.2.1
  # sidekiq:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - rails
  #     - database
  #     - redis
  #   volumes:
  #     - ./rails/app:/app
  #     # - ./script_api/gem_cache:/usr/local/bundle/gems
  #     # - ./script_api/node_modules:/app/node_modules
  #   env_file: ./rails/app/.env
  #   environment:
  #     RAILS_ENV: development
  #   entrypoint: ./entrypoints/sidekiq-entrypoint.sh
volumes:
  dbdata:
  railsapp:
secrets:
  dbpassword:
    file: database/password.txt  
