version: '3.4'

services:
  database:
    image: postgres:12.6
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - database
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./script_api:/app
      # - ./script_api/gem_cache:/usr/local/bundle/gems
      # - ./script_api/node_modules:/app/node_modules
    env_file: ./script_api/.env
    environment:
      RAILS_ENV: development
  redis:
    image: redis:5.0.7
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
      - database
      - redis
    volumes:
      - ./script_api:/app
      # - ./script_api/gem_cache:/usr/local/bundle/gems
      # - ./script_api/node_modules:/app/node_modules
    env_file: ./script_api/.env
    environment:
      RAILS_ENV: development
    entrypoint: sidekiq-entrypoint.sh
volumes:
  dbdata:
  # gem_cache:
  # node_modules: